namespace:
  name: staging
 
service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: 0906784480/techtrends 
  tag: latest
  pullPolicy: IfNotPresent
  
replicaCount: 1
resources:
  request:
    memory: 64Mi
    CPU: 200m
  limits:
    memory: 128Mi
    CPU: 300m
containerPort: 3111
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
  
