namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: 0906784480/techtrends 
  tag: latest
  pullPolicy: IfNotPresent
  
replicaCount: 1
resources:
  request:
    memory: 64Mi
    CPU: 250M
  limits:
    memory: 128Mi
    CPU: 500M
containerPort: 3111
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
  
